// user
export const USER_SET_USER_TOKEN = "USER_SET_USER_TOKEN"; // 设置token
export const USER_SET_USER_INFO = "USER_SET_USER_INFO"; // 设置user 
export const USER_RESET_USER = "USER_RESET_USER"; // 重置

// tags
export const TAGSVIEW_ADD_TAG = "TAGSVIEW_ADD_TAG";
export const TAGSVIEW_DELETE_TAG = "TAGSVIEW_DELETE_TAG";
export const TAGSVIEW_EMPTY_TAGLIST = "TAGSVIEW_EMPTY_TAGLIST";
export const TAGSVIEW_CLOSE_OTHER_TAGS = "TAGSVIEW_CLOSE_OTHER_TAGS";
